export type PolicySlug = "privacy-policy" | "terms-and-conditions" | "return-and-refund-policy" | "shipment-policy"

export type PolicyParagraphStyle = "" | "Heading2" | "Heading3" | "Heading4" | "ListParagraph" | "ListBullet"

export type PolicyParagraph = {
  readonly type: "paragraph"
  readonly style: PolicyParagraphStyle
  readonly text: string
}

export type PolicyTable = {
  readonly type: "table"
  readonly rows: readonly (readonly string[])[]
}

export type PolicyItem = PolicyParagraph | PolicyTable

export type PolicyDocument = {
  readonly slug: PolicySlug
  readonly title: string
  readonly navLabel: string
  readonly updatedAt: string
  readonly body: readonly PolicyItem[]
}

export const POLICY_DOCUMENTS = [
  {
    "slug": "privacy-policy",
    "title": "Privacy Policy",
    "navLabel": "Privacy Policy",
    "updatedAt": "Last updated: July 02, 2026",
    "body": [
      {
        "type": "paragraph",
        "style": "",
        "text": "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. "
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Interpretation and Definitions"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Interpretation"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Definitions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "For the purposes of this Privacy Policy:"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Account means a unique account created for You to access our Service or parts of our Service."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Affiliate means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Smart Enterprises, Mullanpara, Manjeri, Kerala, India 676121."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Country refers to: Kerala, India"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Personal Data is any information that relates to an identified or identifiable individual."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Service refers to the Website."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Website refers to www.neogrid.in, accessible from www.neogrid.in"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Collecting and Using Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Types of Data Collected"
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Email address"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "First name and last name"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Phone number"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Address, State, Province, ZIP/Postal code, City"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Usage Data"
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Usage Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Usage Data is collected automatically when using the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device."
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Information from Third-Party Social Media Services"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Google"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Facebook"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Instagram"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Twitter"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "LinkedIn"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Pinterest "
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy."
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Tracking Technologies and Cookies"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Cookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We use both Session and Persistent Cookies for the purposes set out below:"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Necessary / Essential Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Type: Session Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Administered by: Us"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Cookies Policy / Notice Acceptance Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Type: Persistent Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Administered by: Us"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Purpose: These Cookies identify if users have accepted the use of cookies on the Website."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Functionality Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Type: Persistent Cookies"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Administered by: Us"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Use of Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company may use Personal Data for the following purposes:"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "To provide and maintain our Service, including to monitor the usage of our Service."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "To manage Your requests: To attend and manage Your requests to Us."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We may share Your personal information in the following situations:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "With Your consent: We may disclose Your personal information for any other purpose with Your consent."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Retention of Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Transfer of Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Delete Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Our Service may give You the ability to delete certain information about You from within the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Disclosure of Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Business Transactions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy."
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Law enforcement"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)."
      },
      {
        "type": "paragraph",
        "style": "Heading4",
        "text": "Other legal requirements"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Comply with a legal obligation"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Protect and defend the rights or property of the Company"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Prevent or investigate possible wrongdoing in connection with the Service"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Protect the personal safety of Users of the Service or the public"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "Protect against legal liability"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Security of Your Personal Data"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Children's Privacy"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Links to Other Websites"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Changes to this Privacy Policy"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Contact Us"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If you have any questions about this Privacy Policy, You can contact us:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "By email: info@neogrid.in"
      }
    ]
  },
  {
    "slug": "terms-and-conditions",
    "title": "Terms and Conditions",
    "navLabel": "Terms & Conditions",
    "updatedAt": "Last updated: July 02, 2024",
    "body": [
      {
        "type": "paragraph",
        "style": "",
        "text": "Please read these terms and conditions carefully before using Our Service."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Interpretation and Definitions"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Interpretation"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Definitions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "For the purposes of these Terms and Conditions:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Affiliate means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Country refers to: Kerala, India"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Smart Enterprises, Mullanpara, Manjeri, Kerala, India 676121."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Service refers to the Website."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Terms and Conditions (also referred as \"Terms\") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Third-party Social Media Service means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Website refers to www.neogrid.in, accessible from www.neogrid.in"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Acknowledgment"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Links to Other Websites"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Termination"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Upon termination, Your right to use the Service will cease immediately."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Limitation of Liability"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased anything through the Service."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party's liability will be limited to the greatest extent permitted by law."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "\"AS IS\" and \"AS AVAILABLE\" Disclaimer"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The Service is provided to You \"AS IS\" and \"AS AVAILABLE\" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Governing Law"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Disputes Resolution"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "For European Union (EU) Users"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which You are resident."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "United States Legal Compliance"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a \"terrorist supporting\" country, and (ii) You are not listed on any United States government list of prohibited or restricted parties."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Severability and Waiver"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Severability"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Waiver"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Translation Interpretation"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "These Terms and Conditions may have been translated if We have made them available to You on our Service. You agree that the original English text shall prevail in the case of a dispute."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Changes to These Terms and Conditions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Contact Us"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If you have any questions about these Terms and Conditions, You can contact us:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "By email: info@neogrid.in"
      }
    ]
  },
  {
    "slug": "return-and-refund-policy",
    "title": "Return and Refund Policy",
    "navLabel": "Refund & Return Policy",
    "updatedAt": "Last updated: July 02, 2024",
    "body": [
      {
        "type": "paragraph",
        "style": "",
        "text": "Thank you for shopping at www.neogrid.in"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns. The following terms are applicable for any products that You purchased with Us."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Interpretation and Definitions"
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Interpretation"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Definitions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "For the purposes of this Return and Refund Policy:"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Smart Enterprises, Mullanpara, Manjeri, Kerala, India 676121."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Goods refer to the items offered for sale on the Service."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Orders mean a request by You to purchase Goods from Us."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Service refers to the Website."
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "Website refers to www.neogrid.in, accessible from www.neogrid.in"
      },
      {
        "type": "paragraph",
        "style": "ListParagraph",
        "text": "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Your Order Cancellation Rights"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You are entitled to cancel Your Order within 7 days without giving any reason for doing so."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The deadline for cancelling an Order is 7 days from the date on which You received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform us of your decision by:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "By email: info@noegrid.in"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Conditions for Returns"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "In order for the Goods to be eligible for a return, please make sure that:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The Goods were purchased in the last 7 days"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The Goods are in the original packaging"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "The following Goods cannot be returned:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The supply of Goods made to Your specifications or clearly personalized."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The supply of Goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The supply of Goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery."
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "The supply of Goods which are, after delivery, according to their nature, inseparably mixed with other items."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We reserve the right to refuse returns of any merchandise that does not meet the above return conditions in our sole discretion."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Only regular priced Goods may be refunded. Unfortunately, Goods on sale cannot be refunded. This exclusion may not apply to You if it is not permitted by applicable law."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Returning Goods"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You are responsible for the cost and risk of returning the Goods to Us. You should send the Goods at the following address:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Mullanpara, Manjeri, Kerala, India 676121"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We cannot be held responsible for Goods damaged or lost in return shipment. Therefore, We recommend an insured and trackable mail service. We are unable to issue a refund without actual receipt of the Goods or proof of received return delivery."
      },
      {
        "type": "paragraph",
        "style": "Heading2",
        "text": "Gifts"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If the Goods were marked as a gift when purchased and then shipped directly to you, You'll receive a gift credit for the value of your return. Once the returned product is received, a gift certificate will be mailed to You."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If the Goods weren't marked as a gift when purchased, or the gift giver had the Order shipped to themselves to give it to You later, We will send the refund to the gift giver."
      },
      {
        "type": "paragraph",
        "style": "Heading3",
        "text": "Contact Us"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If you have any questions about our Returns and Refunds Policy, please contact us:"
      },
      {
        "type": "paragraph",
        "style": "ListBullet",
        "text": "By email: info@neogrid.in"
      }
    ]
  },
  {
    "slug": "shipment-policy",
    "title": "Shipping Policy",
    "navLabel": "Shipment Policy",
    "updatedAt": "Effective Date: July 2, 2026",
    "body": [
      {
        "type": "paragraph",
        "style": "",
        "text": "Thank you for choosing NeoGrid ( www.neogrid.in) . We are committed to delivering your solar products and related equipment safely and efficiently. This Shipping Policy outlines our shipping procedures, delivery timelines, and customer responsibilities."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "1. Order Processing"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "All orders are processed after successful payment confirmation.Standard products are generally processed within 1–3 business days. Custom solar solutions, rooftop systems, commercial installations, and bulk orders may require additional processing time depending on project specifications and product availability. Customers will be informed of any significant delay in processing."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "2. Shipping Coverage"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "NeoGrid ships products across India, subject to service availability by our logistics partners."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Delivery to remote or difficult-to-access locations may require additional transit time."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "3. Delivery Timeline"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Estimated delivery times are as follows:"
      },
      {
        "type": "table",
        "rows": [
          [
            "Location",
            "Estimated Delivery Time"
          ],
          [
            "Major Metro Cities",
            "3–7 Business Days"
          ],
          [
            "Other Cities & Towns",
            "5–10 Business Days"
          ],
          [
            "Remote Locations",
            "7–15 Business Days"
          ]
        ]
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Please note that delivery timelines are estimates and may vary due to weather conditions, transportation issues, government regulations, or other unforeseen circumstances."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "4. Shipping Charges"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Shipping charges, if applicable, will be displayed during checkout or communicated before order confirmation."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Certain products, promotional offers, or minimum order values may qualify for free shipping."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Heavy items such as solar panels, batteries, mounting structures, and commercial equipment may incur additional freight charges depending on weight, quantity, and delivery location."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "5. Shipment Tracking"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Once your order has been dispatched, you will receive shipment confirmation via email or phone, including tracking details where applicable."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "You can use the provided tracking information to monitor your shipment until delivery."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "6. Delivery Inspection"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Upon receiving your shipment, please inspect the package carefully before accepting delivery."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If the package appears damaged, tampered with, or incomplete:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Note the issue with the delivery personnel (where possible)."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Take clear photographs of the package and product."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Contact NeoGrid immediately for assistance."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "7. Delayed Deliveries"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Although we strive to deliver every order within the estimated timeframe, delays may occur due to:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Natural disasters"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Severe weather conditions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Transportation disruptions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Government restrictions"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Public holidays"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* High order volumes"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Circumstances beyond our reasonable control"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "NeoGrid will make every effort to keep customers informed regarding any significant delays."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "8. Incorrect Shipping Information"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Customers are responsible for providing complete and accurate shipping information."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "NeoGrid shall not be liable for delays or failed deliveries resulting from incorrect or incomplete shipping addresses. Additional shipping charges may apply for re-dispatch of returned shipments."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "9. Damaged, Lost, or Missing Shipments"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If your shipment arrives damaged, incomplete, or appears to be lost during transit, please notify us within 48 hours of delivery or the expected delivery date."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Please provide:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Order details"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Photographs of the package (if damaged)"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "* Description of the issue"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Our support team will investigate the matter and provide an appropriate resolution, including replacement or other suitable remedies where applicable."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "10. Installation-Based Deliveries"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "For rooftop solar installations and large commercial or industrial projects, delivery schedules are coordinated directly with the customer as part of the project planning process."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Installation dates and delivery timelines will be communicated separately by the NeoGrid project team."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "11. Contact Us"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "If you have any questions regarding shipping, delivery, or your order, please contact us:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "NeoGrid"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Email:info@neogrid.in"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Address:"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "MM 11/505-C, Mullampara,"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Manjeri, Malappuram,"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "Kerala – 676121, India"
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "We appreciate your trust in NeoGrid and are committed to ensuring a smooth and reliable delivery experience."
      },
      {
        "type": "paragraph",
        "style": "",
        "text": "***"
      }
    ]
  }
] as const satisfies readonly PolicyDocument[]

export const POLICY_LINKS = POLICY_DOCUMENTS.map(({ slug, navLabel }) => ({
  slug,
  label: navLabel,
  href: `/${slug}`,
}))

export function getPolicyDocument(slug: PolicySlug) {
  return POLICY_DOCUMENTS.find((document) => document.slug === slug)
}
